[tool.poetry]
authors = ["Dan Fritchman <dan@fritch.mn>"]
description = "VLSIR Chip-Design Schema Bindings"
name = "vlsir"
version = "0.1.1-dev0"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
protobuf = "^3.19.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
