// source: geometry.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.vlsirlol.Geometry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vlsirlol.Cell');
goog.require('proto.vlsirlol.Instance');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vlsirlol.Geometry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vlsirlol.Geometry.repeatedFields_, null);
};
goog.inherits(proto.vlsirlol.Geometry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vlsirlol.Geometry.displayName = 'proto.vlsirlol.Geometry';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vlsirlol.Geometry.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vlsirlol.Geometry.prototype.toObject = function(opt_includeInstance) {
  return proto.vlsirlol.Geometry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vlsirlol.Geometry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsirlol.Geometry.toObject = function(includeInstance, msg) {
  var f, obj = {
    topInstance: (f = msg.getTopInstance()) && proto.vlsirlol.Instance.toObject(includeInstance, f),
    cellsList: jspb.Message.toObjectList(msg.getCellsList(),
    proto.vlsirlol.Cell.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vlsirlol.Geometry}
 */
proto.vlsirlol.Geometry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vlsirlol.Geometry;
  return proto.vlsirlol.Geometry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vlsirlol.Geometry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vlsirlol.Geometry}
 */
proto.vlsirlol.Geometry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.vlsirlol.Instance;
      reader.readMessage(value,proto.vlsirlol.Instance.deserializeBinaryFromReader);
      msg.setTopInstance(value);
      break;
    case 2:
      var value = new proto.vlsirlol.Cell;
      reader.readMessage(value,proto.vlsirlol.Cell.deserializeBinaryFromReader);
      msg.addCells(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vlsirlol.Geometry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vlsirlol.Geometry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vlsirlol.Geometry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsirlol.Geometry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopInstance();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.vlsirlol.Instance.serializeBinaryToWriter
    );
  }
  f = message.getCellsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.vlsirlol.Cell.serializeBinaryToWriter
    );
  }
};


/**
 * optional Instance top_instance = 1;
 * @return {?proto.vlsirlol.Instance}
 */
proto.vlsirlol.Geometry.prototype.getTopInstance = function() {
  return /** @type{?proto.vlsirlol.Instance} */ (
    jspb.Message.getWrapperField(this, proto.vlsirlol.Instance, 1));
};


/**
 * @param {?proto.vlsirlol.Instance|undefined} value
 * @return {!proto.vlsirlol.Geometry} returns this
*/
proto.vlsirlol.Geometry.prototype.setTopInstance = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsirlol.Geometry} returns this
 */
proto.vlsirlol.Geometry.prototype.clearTopInstance = function() {
  return this.setTopInstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsirlol.Geometry.prototype.hasTopInstance = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Cell cells = 2;
 * @return {!Array<!proto.vlsirlol.Cell>}
 */
proto.vlsirlol.Geometry.prototype.getCellsList = function() {
  return /** @type{!Array<!proto.vlsirlol.Cell>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vlsirlol.Cell, 2));
};


/**
 * @param {!Array<!proto.vlsirlol.Cell>} value
 * @return {!proto.vlsirlol.Geometry} returns this
*/
proto.vlsirlol.Geometry.prototype.setCellsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.vlsirlol.Cell=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vlsirlol.Cell}
 */
proto.vlsirlol.Geometry.prototype.addCells = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.vlsirlol.Cell, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vlsirlol.Geometry} returns this
 */
proto.vlsirlol.Geometry.prototype.clearCellsList = function() {
  return this.setCellsList([]);
};


