/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vlsir.tech.LayerInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vlsir.tech.LayerPurpose');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vlsir.tech.LayerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vlsir.tech.LayerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vlsir.tech.LayerInfo.displayName = 'proto.vlsir.tech.LayerInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vlsir.tech.LayerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.vlsir.tech.LayerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vlsir.tech.LayerInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.tech.LayerInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purpose: (f = msg.getPurpose()) && proto.vlsir.tech.LayerPurpose.toObject(includeInstance, f),
    index: jspb.Message.getFieldWithDefault(msg, 21, 0),
    subIndex: jspb.Message.getFieldWithDefault(msg, 31, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vlsir.tech.LayerInfo}
 */
proto.vlsir.tech.LayerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vlsir.tech.LayerInfo;
  return proto.vlsir.tech.LayerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vlsir.tech.LayerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vlsir.tech.LayerInfo}
 */
proto.vlsir.tech.LayerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 11:
      var value = new proto.vlsir.tech.LayerPurpose;
      reader.readMessage(value,proto.vlsir.tech.LayerPurpose.deserializeBinaryFromReader);
      msg.setPurpose(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIndex(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSubIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vlsir.tech.LayerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vlsir.tech.LayerInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vlsir.tech.LayerInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.tech.LayerInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurpose();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.vlsir.tech.LayerPurpose.serializeBinaryToWriter
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeUint64(
      21,
      f
    );
  }
  f = message.getSubIndex();
  if (f !== 0) {
    writer.writeUint64(
      31,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.vlsir.tech.LayerInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.vlsir.tech.LayerInfo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LayerPurpose purpose = 11;
 * @return {?proto.vlsir.tech.LayerPurpose}
 */
proto.vlsir.tech.LayerInfo.prototype.getPurpose = function() {
  return /** @type{?proto.vlsir.tech.LayerPurpose} */ (
    jspb.Message.getWrapperField(this, proto.vlsir.tech.LayerPurpose, 11));
};


/** @param {?proto.vlsir.tech.LayerPurpose|undefined} value */
proto.vlsir.tech.LayerInfo.prototype.setPurpose = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.vlsir.tech.LayerInfo.prototype.clearPurpose = function() {
  this.setPurpose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.vlsir.tech.LayerInfo.prototype.hasPurpose = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional uint64 index = 21;
 * @return {number}
 */
proto.vlsir.tech.LayerInfo.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {number} value */
proto.vlsir.tech.LayerInfo.prototype.setIndex = function(value) {
  jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional uint64 sub_index = 31;
 * @return {number}
 */
proto.vlsir.tech.LayerInfo.prototype.getSubIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/** @param {number} value */
proto.vlsir.tech.LayerInfo.prototype.setSubIndex = function(value) {
  jspb.Message.setProto3IntField(this, 31, value);
};


