/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vlsir.spice.SimOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vlsir.spice.SimOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vlsir.spice.SimOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vlsir.spice.SimOptions.displayName = 'proto.vlsir.spice.SimOptions';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vlsir.spice.SimOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.vlsir.spice.SimOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vlsir.spice.SimOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.spice.SimOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    temp: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    tnom: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    gmin: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    iabstol: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    reltol: +jspb.Message.getFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vlsir.spice.SimOptions}
 */
proto.vlsir.spice.SimOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vlsir.spice.SimOptions;
  return proto.vlsir.spice.SimOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vlsir.spice.SimOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vlsir.spice.SimOptions}
 */
proto.vlsir.spice.SimOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTemp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTnom(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGmin(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setIabstol(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setReltol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vlsir.spice.SimOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vlsir.spice.SimOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vlsir.spice.SimOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.spice.SimOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTemp();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getTnom();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getGmin();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getIabstol();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getReltol();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional double temp = 1;
 * @return {number}
 */
proto.vlsir.spice.SimOptions.prototype.getTemp = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.vlsir.spice.SimOptions.prototype.setTemp = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double tnom = 2;
 * @return {number}
 */
proto.vlsir.spice.SimOptions.prototype.getTnom = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.vlsir.spice.SimOptions.prototype.setTnom = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double gmin = 3;
 * @return {number}
 */
proto.vlsir.spice.SimOptions.prototype.getGmin = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.vlsir.spice.SimOptions.prototype.setGmin = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double iabstol = 4;
 * @return {number}
 */
proto.vlsir.spice.SimOptions.prototype.getIabstol = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.vlsir.spice.SimOptions.prototype.setIabstol = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double reltol = 5;
 * @return {number}
 */
proto.vlsir.spice.SimOptions.prototype.getReltol = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.vlsir.spice.SimOptions.prototype.setReltol = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


