// source: spice.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vlsir.spice.SimOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.DoubleValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vlsir.spice.SimOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vlsir.spice.SimOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vlsir.spice.SimOptions.displayName = 'proto.vlsir.spice.SimOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vlsir.spice.SimOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.vlsir.spice.SimOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vlsir.spice.SimOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.spice.SimOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    temp: (f = msg.getTemp()) && proto.google.protobuf.DoubleValue.toObject(includeInstance, f),
    tnom: (f = msg.getTnom()) && proto.google.protobuf.DoubleValue.toObject(includeInstance, f),
    gmin: (f = msg.getGmin()) && proto.google.protobuf.DoubleValue.toObject(includeInstance, f),
    iabstol: (f = msg.getIabstol()) && proto.google.protobuf.DoubleValue.toObject(includeInstance, f),
    reltol: (f = msg.getReltol()) && proto.google.protobuf.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vlsir.spice.SimOptions}
 */
proto.vlsir.spice.SimOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vlsir.spice.SimOptions;
  return proto.vlsir.spice.SimOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vlsir.spice.SimOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vlsir.spice.SimOptions}
 */
proto.vlsir.spice.SimOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.DoubleValue;
      reader.readMessage(value,proto.google.protobuf.DoubleValue.deserializeBinaryFromReader);
      msg.setTemp(value);
      break;
    case 2:
      var value = new proto.google.protobuf.DoubleValue;
      reader.readMessage(value,proto.google.protobuf.DoubleValue.deserializeBinaryFromReader);
      msg.setTnom(value);
      break;
    case 3:
      var value = new proto.google.protobuf.DoubleValue;
      reader.readMessage(value,proto.google.protobuf.DoubleValue.deserializeBinaryFromReader);
      msg.setGmin(value);
      break;
    case 4:
      var value = new proto.google.protobuf.DoubleValue;
      reader.readMessage(value,proto.google.protobuf.DoubleValue.deserializeBinaryFromReader);
      msg.setIabstol(value);
      break;
    case 5:
      var value = new proto.google.protobuf.DoubleValue;
      reader.readMessage(value,proto.google.protobuf.DoubleValue.deserializeBinaryFromReader);
      msg.setReltol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vlsir.spice.SimOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vlsir.spice.SimOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vlsir.spice.SimOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.spice.SimOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTemp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTnom();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getGmin();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getIabstol();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getReltol();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.DoubleValue temp = 1;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.vlsir.spice.SimOptions.prototype.getTemp = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DoubleValue, 1));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.vlsir.spice.SimOptions} returns this
*/
proto.vlsir.spice.SimOptions.prototype.setTemp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.spice.SimOptions} returns this
 */
proto.vlsir.spice.SimOptions.prototype.clearTemp = function() {
  return this.setTemp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.spice.SimOptions.prototype.hasTemp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.DoubleValue tnom = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.vlsir.spice.SimOptions.prototype.getTnom = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DoubleValue, 2));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.vlsir.spice.SimOptions} returns this
*/
proto.vlsir.spice.SimOptions.prototype.setTnom = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.spice.SimOptions} returns this
 */
proto.vlsir.spice.SimOptions.prototype.clearTnom = function() {
  return this.setTnom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.spice.SimOptions.prototype.hasTnom = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue gmin = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.vlsir.spice.SimOptions.prototype.getGmin = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DoubleValue, 3));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.vlsir.spice.SimOptions} returns this
*/
proto.vlsir.spice.SimOptions.prototype.setGmin = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.spice.SimOptions} returns this
 */
proto.vlsir.spice.SimOptions.prototype.clearGmin = function() {
  return this.setGmin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.spice.SimOptions.prototype.hasGmin = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue iabstol = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.vlsir.spice.SimOptions.prototype.getIabstol = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DoubleValue, 4));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.vlsir.spice.SimOptions} returns this
*/
proto.vlsir.spice.SimOptions.prototype.setIabstol = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.spice.SimOptions} returns this
 */
proto.vlsir.spice.SimOptions.prototype.clearIabstol = function() {
  return this.setIabstol(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.spice.SimOptions.prototype.hasIabstol = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue reltol = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.vlsir.spice.SimOptions.prototype.getReltol = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DoubleValue, 5));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.vlsir.spice.SimOptions} returns this
*/
proto.vlsir.spice.SimOptions.prototype.setReltol = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.spice.SimOptions} returns this
 */
proto.vlsir.spice.SimOptions.prototype.clearReltol = function() {
  return this.setReltol(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.spice.SimOptions.prototype.hasReltol = function() {
  return jspb.Message.getField(this, 5) != null;
};


