// source: tetris.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.vlsir.tetris.ViaLayer');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vlsir.raw.Layer');
goog.require('proto.vlsir.tetris.LayerEnum');
goog.require('proto.vlsir.tetris.Xy');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vlsir.tetris.ViaLayer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vlsir.tetris.ViaLayer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vlsir.tetris.ViaLayer.displayName = 'proto.vlsir.tetris.ViaLayer';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vlsir.tetris.ViaLayer.prototype.toObject = function(opt_includeInstance) {
  return proto.vlsir.tetris.ViaLayer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vlsir.tetris.ViaLayer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.tetris.ViaLayer.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    top: (f = msg.getTop()) && proto.vlsir.tetris.LayerEnum.toObject(includeInstance, f),
    bot: (f = msg.getBot()) && proto.vlsir.tetris.LayerEnum.toObject(includeInstance, f),
    size: (f = msg.getSize()) && proto.vlsir.tetris.Xy.toObject(includeInstance, f),
    raw: (f = msg.getRaw()) && proto.vlsir.raw.Layer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vlsir.tetris.ViaLayer}
 */
proto.vlsir.tetris.ViaLayer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vlsir.tetris.ViaLayer;
  return proto.vlsir.tetris.ViaLayer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vlsir.tetris.ViaLayer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vlsir.tetris.ViaLayer}
 */
proto.vlsir.tetris.ViaLayer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.vlsir.tetris.LayerEnum;
      reader.readMessage(value,proto.vlsir.tetris.LayerEnum.deserializeBinaryFromReader);
      msg.setTop(value);
      break;
    case 3:
      var value = new proto.vlsir.tetris.LayerEnum;
      reader.readMessage(value,proto.vlsir.tetris.LayerEnum.deserializeBinaryFromReader);
      msg.setBot(value);
      break;
    case 4:
      var value = new proto.vlsir.tetris.Xy;
      reader.readMessage(value,proto.vlsir.tetris.Xy.deserializeBinaryFromReader);
      msg.setSize(value);
      break;
    case 11:
      var value = new proto.vlsir.raw.Layer;
      reader.readMessage(value,proto.vlsir.raw.Layer.deserializeBinaryFromReader);
      msg.setRaw(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vlsir.tetris.ViaLayer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vlsir.tetris.ViaLayer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vlsir.tetris.ViaLayer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vlsir.tetris.ViaLayer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTop();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.vlsir.tetris.LayerEnum.serializeBinaryToWriter
    );
  }
  f = message.getBot();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.vlsir.tetris.LayerEnum.serializeBinaryToWriter
    );
  }
  f = message.getSize();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.vlsir.tetris.Xy.serializeBinaryToWriter
    );
  }
  f = message.getRaw();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.vlsir.raw.Layer.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.vlsir.tetris.ViaLayer.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
 */
proto.vlsir.tetris.ViaLayer.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LayerEnum top = 2;
 * @return {?proto.vlsir.tetris.LayerEnum}
 */
proto.vlsir.tetris.ViaLayer.prototype.getTop = function() {
  return /** @type{?proto.vlsir.tetris.LayerEnum} */ (
    jspb.Message.getWrapperField(this, proto.vlsir.tetris.LayerEnum, 2));
};


/**
 * @param {?proto.vlsir.tetris.LayerEnum|undefined} value
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
*/
proto.vlsir.tetris.ViaLayer.prototype.setTop = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
 */
proto.vlsir.tetris.ViaLayer.prototype.clearTop = function() {
  return this.setTop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.tetris.ViaLayer.prototype.hasTop = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LayerEnum bot = 3;
 * @return {?proto.vlsir.tetris.LayerEnum}
 */
proto.vlsir.tetris.ViaLayer.prototype.getBot = function() {
  return /** @type{?proto.vlsir.tetris.LayerEnum} */ (
    jspb.Message.getWrapperField(this, proto.vlsir.tetris.LayerEnum, 3));
};


/**
 * @param {?proto.vlsir.tetris.LayerEnum|undefined} value
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
*/
proto.vlsir.tetris.ViaLayer.prototype.setBot = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
 */
proto.vlsir.tetris.ViaLayer.prototype.clearBot = function() {
  return this.setBot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.tetris.ViaLayer.prototype.hasBot = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Xy size = 4;
 * @return {?proto.vlsir.tetris.Xy}
 */
proto.vlsir.tetris.ViaLayer.prototype.getSize = function() {
  return /** @type{?proto.vlsir.tetris.Xy} */ (
    jspb.Message.getWrapperField(this, proto.vlsir.tetris.Xy, 4));
};


/**
 * @param {?proto.vlsir.tetris.Xy|undefined} value
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
*/
proto.vlsir.tetris.ViaLayer.prototype.setSize = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
 */
proto.vlsir.tetris.ViaLayer.prototype.clearSize = function() {
  return this.setSize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.tetris.ViaLayer.prototype.hasSize = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional vlsir.raw.Layer raw = 11;
 * @return {?proto.vlsir.raw.Layer}
 */
proto.vlsir.tetris.ViaLayer.prototype.getRaw = function() {
  return /** @type{?proto.vlsir.raw.Layer} */ (
    jspb.Message.getWrapperField(this, proto.vlsir.raw.Layer, 11));
};


/**
 * @param {?proto.vlsir.raw.Layer|undefined} value
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
*/
proto.vlsir.tetris.ViaLayer.prototype.setRaw = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vlsir.tetris.ViaLayer} returns this
 */
proto.vlsir.tetris.ViaLayer.prototype.clearRaw = function() {
  return this.setRaw(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vlsir.tetris.ViaLayer.prototype.hasRaw = function() {
  return jspb.Message.getField(this, 11) != null;
};


