name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: tpluck95/vlsir-test-container
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout VLSIR Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          apt-get update
          apt-get install -y python${{ matrix.python-version }}
          apt-get install -y python${{ matrix.python-version }}-dev
          apt-get install -y python${{ matrix.python-version }}-venv
          # Only install distutils for Python versions below 3.12
          if [[ "${{ matrix.python-version }}" < "3.12" ]]; then
            apt-get install -y python${{ matrix.python-version }}-distutils || true
          fi
          # For Python 3.12, install setuptools which replaces distutils functionality
          if [[ "${{ matrix.python-version }}" > "3.11" ]]; then
            python${{ matrix.python-version }} -m ensurepip --upgrade || true
            python${{ matrix.python-version }} -m pip install setuptools
          fi

      #! The bizarre insanity of ". ./venv/..." is an Ubuntu sh translation of
      #! "source venv/..." seen in most Python documentation
      - name: pytest `bindings/python`
        run: |
          python${{ matrix.python-version }} -m venv ./venv
          . ./venv/bin/activate
          cd bindings/python
          python${{ matrix.python-version }} -m pip install -e ".[dev]"
          python${{ matrix.python-version }} -m pytest -sv --cov=./ --cov-report=xml

      - name: pytest `VlsirTools`
        run: |
          python${{ matrix.python-version }} -m venv ./venv
          . ./venv/bin/activate
          cd VlsirTools
          python${{ matrix.python-version }} -m pip install -e ".[dev]"
          python${{ matrix.python-version }} -m pytest -sv --cov=./ --cov-report=xml --simulator_test_mode required --spectre disabled

  check-formatting:
    name: Black Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          version: "22.6"
          options: "--check --diff --verbose --exclude bindings/"

  build-bindings:
    name: Build Bindings
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install 2to3, protobuf and black
        run: pip3 install 2to3 protobuf black

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install TypeScript Dependencies
        run: yarn
        working-directory: bindings/ts/

      - name: Run build script
        run: scripts/build_all_recipes.sh